### ISSUE TITLE
Console Warning with Feature-Policy header

### ISSUE THREAD

**Issue by alexanderrudnik** [altence/lightence-ant-design-react-template#202] opened 2022-02-07 13:18 UTC
**Describe the bug**
There is a console warning (error) once the user opens any page

"
Error with Feature-Policy header: Unrecognized feature: 'none'.
"

**Screenshots**
![image](https://user-images.githubusercontent.com/9514327/152795368-72845e76-4470-4359-9d1e-6d5f57c8f270.png)

**Comment by leineveber** [comment] 2022-09-07 12:44
can't reproduce

**Comment by leineveber** [comment] 2023-02-21 11:23
still can't reproduce, closing
if you still have the warning, please open new issue with steps to reproduce

**Closed by leineveber** 2023-02-21 11:23 UTC
Labels: bug
